# -*- coding: utf-8 -*-
"""newsapi sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkpXmikyDCCiUhwuSgMFvjVVvMiDB9DY
"""

import requests
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk

# Download VADER for sentiment analysis
nltk.download('vader_lexicon')

# Your News API key
API_KEY = '917931d6b9dd483bb18622b5d2251b55'  # Replace with your actual News API key

# Function to fetch news articles based on company name
def fetch_news_articles(company_name):
    url = f'https://newsapi.org/v2/everything?q={company_name}&apiKey={API_KEY}'
    response = requests.get(url)
    if response.status_code == 200:
        articles = response.json().get('articles', [])
        return articles
    else:
        print(f"Error fetching news: {response.status_code}")
        return []

# Function to perform sentiment analysis
def analyze_sentiment(articles):
    sia = SentimentIntensityAnalyzer()
    sentiments = []

    for article in articles:
        title = article.get('title', '')
        description = article.get('description', '')
        content = (title + ' ' + description).strip()

        # Calculate sentiment scores
        sentiment = sia.polarity_scores(content)
        sentiments.append(sentiment)

    return sentiments

# Function to calculate average sentiment scores
def calculate_average_sentiment(sentiments):
    if not sentiments:
        return None

    avg_sentiment = {
        'neg': 0,
        'neu': 0,
        'pos': 0,
        'compound': 0
    }

    for sentiment in sentiments:
        avg_sentiment['neg'] += sentiment['neg']
        avg_sentiment['neu'] += sentiment['neu']
        avg_sentiment['pos'] += sentiment['pos']
        avg_sentiment['compound'] += sentiment['compound']

    num_sentiments = len(sentiments)
    avg_sentiment = {k: v / num_sentiments for k, v in avg_sentiment.items()}

    return avg_sentiment

# Main function
def main():
    company_name = input("Enter the company name (e.g., 'Apple', 'Google'): ").strip()

    # Fetch news articles
    articles = fetch_news_articles(company_name)

    if not articles:
        print("No articles found.")
        return

    # Perform sentiment analysis
    sentiment_results = analyze_sentiment(articles)

    # Calculate average sentiment scores
    avg_sentiment = calculate_average_sentiment(sentiment_results)

    if avg_sentiment:
        print("\nAverage Sentiment Scores:")
        print(f"Negative: {avg_sentiment['neg']:.4f}")
        print(f"Neutral: {avg_sentiment['neu']:.4f}")
        print(f"Positive: {avg_sentiment['pos']:.4f}")
        print(f"Compound: {avg_sentiment['compound']:.4f}")

# Example usage
if __name__ == "__main__":
    main()

import requests
from textblob import TextBlob
from datetime import datetime, timedelta
import matplotlib.pyplot as plt

API_KEY = '917931d6b9dd483bb18622b5d2251b55'

def fetch_news_articles(company_name, from_date, to_date):
    url = f'https://newsapi.org/v2/everything?q={company_name}&from={from_date}&to={to_date}&apiKey={API_KEY}&language=en&sortBy=relevancy'
    response = requests.get(url)

    if response.status_code == 200:
        articles = response.json().get('articles', [])
        return articles
    else:
        print(f"Error fetching news: {response.status_code}")
        return []

def analyze_sentiment(articles):
    positive_sentiment = 0
    negative_sentiment = 0
    neutral_sentiment = 0
    total_sentiment = 0
    count = 0

    for article in articles:
        content = article.get('content')
        if content:
            analysis = TextBlob(content)
            polarity = analysis.sentiment.polarity
            total_sentiment += polarity
            count += 1

            if polarity > 0:
                positive_sentiment += 1
            elif polarity < 0:
                negative_sentiment += 1
            else:
                neutral_sentiment += 1

    if count > 0:
        average_sentiment = total_sentiment / count
        return average_sentiment, positive_sentiment, negative_sentiment, neutral_sentiment, count
    else:
        print("No articles to analyze.")
        return None, 0, 0, 0, 0

def main():
    company_name = input("Enter the company name you want to analyze: ")

    # Set the date range for the last 15 days
    to_date = datetime.now()
    from_date = to_date - timedelta(days=15)

    # Format dates as strings
    to_date_str = to_date.strftime('%Y-%m-%d')
    from_date_str = from_date.strftime('%Y-%m-%d')

    print(f"Analyzing news for {company_name} from {from_date_str} to {to_date_str}...\n")

    articles = fetch_news_articles(company_name, from_date_str, to_date_str)
    average_sentiment, positive_sentiment, negative_sentiment, neutral_sentiment, count = analyze_sentiment(articles)

    if average_sentiment is not None:
        print(f"Total Articles Analyzed: {count}")
        print(f"Positive Sentiment Count: {positive_sentiment}")
        print(f"Negative Sentiment Count: {negative_sentiment}")
        print(f"Neutral Sentiment Count: {neutral_sentiment}")
        print(f"Average Sentiment Polarity: {average_sentiment:.4f}\n")

s

if __name__ == "__main__":
    main()